
//import static cpin.out;
//import static cpin.out;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.applet.*;
import java.io.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author My
 */
public class ammount extends javax.swing.JFrame {
     File wavFile = new File("src\\beep-3.wav");
    AudioClip sound;

    int i=-1;
     int row;
     static String cp[]=new String[20];
    static String out;
    int j;
    char inpass[];
    char pin[]=new char[6];
  public  static double am1;

    /**
     * Creates new form ammount
     */
    public ammount() {
         this.setUndecorated(true);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        double width = toolkit.getScreenSize().getWidth();
        
        double height = toolkit.getScreenSize().getHeight();
        
        this.setSize((int)width, (int)height);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ammount = new javax.swing.JTextField();
        ammount_text = new javax.swing.JLabel();
        wbg = new javax.swing.JLabel();
        atmbg = new javax.swing.JLabel();
        b4 = new javax.swing.JButton();
        bthree = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        ammount.setEditable(false);
        jPanel2.add(ammount);
        ammount.setBounds(620, 280, 190, 40);

        ammount_text.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ammount_text.setText("ENTER  THE  AMOUNT");
        jPanel2.add(ammount_text);
        ammount_text.setBounds(600, 220, 290, 40);

        wbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmbg2.jpg"))); // NOI18N
        jPanel2.add(wbg);
        wbg.setBounds(540, 185, 380, 240);

        atmbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmgif0.jpg"))); // NOI18N
        jPanel2.add(atmbg);
        atmbg.setBounds(370, 0, 720, 780);

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel2.add(b4);
        b4.setBounds(590, 640, 60, 30);

        bthree.setText("3");
        bthree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthreeActionPerformed(evt);
            }
        });
        jPanel2.add(bthree);
        bthree.setBounds(740, 590, 60, 30);

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel2.add(b5);
        b5.setBounds(670, 640, 60, 30);

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel2.add(b0);
        b0.setBounds(670, 740, 60, 30);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);
        b2.setBounds(670, 590, 60, 30);

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel2.add(b7);
        b7.setBounds(590, 690, 60, 30);

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel2.add(b8);
        b8.setBounds(670, 690, 60, 30);

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel2.add(b9);
        b9.setBounds(740, 690, 60, 30);

        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        jPanel2.add(enter);
        enter.setBounds(810, 590, 70, 30);

        clear.setText("clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel2.add(clear);
        clear.setBounds(810, 640, 70, 30);

        cancel.setText("cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel2.add(cancel);
        cancel.setBounds(810, 690, 70, 30);

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel2.add(b6);
        b6.setBounds(740, 640, 60, 30);

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);
        b1.setBounds(590, 590, 60, 30);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1.jpg"))); // NOI18N
        BG.setText("jLabel2");
        jPanel2.add(BG);
        BG.setBounds(0, 0, 1370, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1372, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
             try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='5';
        String string=new String(inpass);
        ammount.setText(string);
        display();                // TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
              try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='7';
        String string=new String(inpass);
        ammount.setText(string);
        display();                // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
             try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='8';
        String string=new String(inpass);
         ammount.setText(string);
        display();                // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
      // }
        pin[i]='1';
        String string=new String(inpass);
       ammount.setText(string);
        display();        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void bthreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthreeActionPerformed
        try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='3';
        String string=new String(inpass);
         ammount.setText(string);
        display();                // TODO add your handling code here:
    }//GEN-LAST:event_bthreeActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='2';
        String string=new String(inpass);
         ammount.setText(string);
        display();        // TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='4';
        String string=new String(inpass);
         ammount.setText(string);
        display();          // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='6';
        String string=new String(inpass);
        ammount.setText(string);
        display();                // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed
        public void display()
    {
           out=new String(pin);
        
      ammount.setText(out);   
    }
         public void displayc()
    {
          out=new String(pin);
        
      ammount.setText(out);   
    }
   
    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='9';
        String string=new String(inpass);
         ammount.setText(string);
        display();                // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
       try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i--;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i+1]='\0';
        String string=new String(inpass);
        ammount.setText(string);
        displayc();        // TODO add your handling code here:
    }//GEN-LAST:event_clearActionPerformed
public void amnt()
{
        am1=Double.parseDouble(ammount.getText());
    
}
        
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
   try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        tpin t1=new tpin();
        amnt();
        
        try {
            t1.get();
        } catch (SQLException ex) {
            Logger.getLogger(ammount.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         t1.setVisible(true);
         dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_enterActionPerformed
public double getAm()
{
    return am1;
}
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
       try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        trans_cancelled t1=new trans_cancelled();
         t1.setVisible(true);
         dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();

        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='0';
        String string=new String(inpass);
         ammount.setText(string);
        display();                
    }//GEN-LAST:event_b0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ammount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ammount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField ammount;
    private javax.swing.JLabel ammount_text;
    private javax.swing.JLabel atmbg;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bthree;
    private javax.swing.JButton cancel;
    private javax.swing.JButton clear;
    private javax.swing.JButton enter;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel wbg;
    // End of variables declaration//GEN-END:variables
}
