import sql1.db;
import java.awt.Button;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.applet.*;
import java.io.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sarve
 */

    

public class cpin extends javax.swing.JFrame {
    File wavFile = new File("src\\beep-3.wav");
    AudioClip sound;
    int i=-1;
     int p=0;
     int m;
     static int h;
    public static double  bal[]=new double[20];
     int row;
    public  String cp[]=new String[20];
    //  String cp_bal[]=new String[20];
    public  String out;
    int j;
    char inpass[];
    char pin[]=new char[6];
    static String name[]=new String[20];
    
    /**
     * Creates new form cpin
     */
    public cpin() {
         this.setUndecorated(true);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        double width = toolkit.getScreenSize().getWidth();
        
        double height = toolkit.getScreenSize().getHeight();
        
        this.setSize((int)width, (int)height);
        
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cpin_txt = new javax.swing.JLabel();
        pinpass = new javax.swing.JPasswordField();
        atmbg = new javax.swing.JLabel();
        main_bg = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        b_enter = new javax.swing.JButton();
        b_clear = new javax.swing.JButton();
        b_cancel = new javax.swing.JButton();
        pin1 = new javax.swing.JTextField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        cpin_txt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cpin_txt.setText("ENTER CUSTOMER PIN");
        jPanel1.add(cpin_txt);
        cpin_txt.setBounds(590, 210, 300, 60);

        pinpass.setEditable(false);
        pinpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pinpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinpassActionPerformed(evt);
            }
        });
        jPanel1.add(pinpass);
        pinpass.setBounds(640, 300, 200, 50);

        atmbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmbg2.jpg"))); // NOI18N
        jPanel1.add(atmbg);
        atmbg.setBounds(540, 185, 380, 240);

        main_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmgif0.jpg"))); // NOI18N
        jPanel1.add(main_bg);
        main_bg.setBounds(370, 0, 720, 780);

        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(590, 590, 70, 30);

        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(670, 590, 60, 30);

        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(740, 590, 60, 30);

        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(590, 640, 70, 30);

        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(670, 640, 60, 30);

        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel1.add(b6);
        b6.setBounds(740, 640, 60, 30);

        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel1.add(b7);
        b7.setBounds(590, 690, 70, 30);

        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel1.add(b8);
        b8.setBounds(670, 690, 60, 30);

        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel1.add(b9);
        b9.setBounds(740, 690, 60, 30);

        b0.setText("0");
        b0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b0ActionPerformed(evt);
            }
        });
        jPanel1.add(b0);
        b0.setBounds(660, 740, 70, 30);

        b_enter.setText("ENTER");
        b_enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_enterActionPerformed(evt);
            }
        });
        jPanel1.add(b_enter);
        b_enter.setBounds(810, 590, 70, 30);

        b_clear.setText("CLEAR");
        b_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_clearActionPerformed(evt);
            }
        });
        jPanel1.add(b_clear);
        b_clear.setBounds(810, 640, 65, 30);

        b_cancel.setText("CANCEL");
        b_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(b_cancel);
        b_cancel.setBounds(810, 690, 70, 30);

        pin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pin1ActionPerformed(evt);
            }
        });
        jPanel1.add(pin1);
        pin1.setBounds(550, 370, 260, 40);

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1.jpg"))); // NOI18N
        jPanel1.add(BG);
        BG.setBounds(-10, 0, 1380, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
       // StringBuilder sb=new StringBuilder();
    //   if(i<7)
     //  {
     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
      // }
        pin[i]='1';
        String string=new String(inpass);
        pinpass.setText(string);
        display();
    }//GEN-LAST:event_b1ActionPerformed
    public void display()
    {
           out=new String(pin);
        
     pin1.setText(out);   
    }
    private void pinpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinpassActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
             try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='2';
        String string=new String(inpass);
        pinpass.setText(string);
        display();
        
    }//GEN-LAST:event_b2ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='9';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        // TODO add your handling code here:
    }//GEN-LAST:event_b9ActionPerformed

    private void b_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelActionPerformed
        // TODO add your handling code here:
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        trans_cancelled t1=new trans_cancelled();
         t1.setVisible(true);
         dispose();
    }//GEN-LAST:event_b_cancelActionPerformed

    private void pin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pin1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='3';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='4';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='5';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='6';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        // TODO add your handling code here:
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='7';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        // TODO add your handling code here:
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='8';
        String string=new String(inpass);
        pinpass.setText(string);
        display();        // TODO add your handling code here:
    }//GEN-LAST:event_b8ActionPerformed

    private void b_enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_enterActionPerformed
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        int a;
        
        try {
            // TODO add your handling code here:
       
            getData();
          a=compare();
          //  System.out.println(out);
            
           // System.out.println(a);
        //   System.out.println(p);
         //   System.out.println(bal[h]);

            if(a==1)
            {
            service ser1=new service();
            ser1.setVisible(true);
            dispose();
            }
            else
            {
                wrongcpin wp1=new wrongcpin();
                 wp1.setVisible(true);
                 dispose();

            }
        } catch (SQLException ex) {
            Logger.getLogger(cpin.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println(p);
        System.out.println(h);
        System.out.println(bal[p]);
       
    }//GEN-LAST:event_b_enterActionPerformed

    private void b_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_clearActionPerformed
        // TODO add your handling code here:
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        i--;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i+1]='\0';
        String string=new String(inpass);
        pinpass.setText(string);
        displayc();
    }//GEN-LAST:event_b_clearActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
                     try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
         i++;
        j=i+1;
        if(j<7)
        {
        inpass=new char[j];
        }
        pin[i]='0';
        String string=new String(inpass);
        pinpass.setText(string);
        display();      
    }//GEN-LAST:event_b0ActionPerformed
    public void displayc()
    {
          out=new String(pin);
        
     pin1.setText(out);   
    }
    public int compare() throws SQLException
    {
        int r=0;
        
       // String str =pin;
       // char ch1 = str.charAt(1);
       
       // System.out.println(cp);
       while(r<=m)  // since 2 rows present in database
         {
          
           
       //System.out.println(cp[r]);
       if(out.equals(cp[r])==true)
        {
           return 1;
            
          //  System.out.println("dhfjhfj");
        }
        r++;
        p++;
        h=p; 
          }
       return 0;/*
       else
        {
             System.out.println("dhfjhfj");
              System.out.println(pin.equals(cp));
              System.out.println();
        } */
       // System.out.println(out);
    }
    public double[] bala()
    {
        return bal;
    }
   public String[] name()
   {
       return name;
   }
    
    public void getData() throws SQLException
    {
        
         db db1=new db();
          cp = db1.db();
           bal=db1.db_bal();
           name=db1.db_name();
           m=db1.row();
                   
        
    
        
    }
    public int disp(){
            return h;
    } 
   
       
    

    /**
     * @param args the command line arguments
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        
        
        
        //    System.out.println("cpin = "+ cp);
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cpin().setVisible(true);
                
            }
       
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel atmbg;
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton b_cancel;
    private javax.swing.JButton b_clear;
    private javax.swing.JButton b_enter;
    private javax.swing.JLabel cpin_txt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel main_bg;
    private javax.swing.JTextField pin1;
    private javax.swing.JPasswordField pinpass;
    // End of variables declaration//GEN-END:variables

    
}
