
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.applet.*;
import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author My
 */
public class wrongtpin extends javax.swing.JFrame {
     File wavFile = new File("src\\beep-3.wav");
    AudioClip sound;


    /**
     * Creates new form wrongtpin
     */
    public wrongtpin() {
        this.setUndecorated(true);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        double width = toolkit.getScreenSize().getWidth();
        
        double height = toolkit.getScreenSize().getHeight();
        
        this.setSize((int)width, (int)height);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EXIT = new javax.swing.JLabel();
        EXIT_ARROW = new javax.swing.JLabel();
        ENTER_PIN_AGAIN = new javax.swing.JLabel();
        ARROWENTER = new javax.swing.JLabel();
        OPTION = new javax.swing.JLabel();
        wrongpin = new javax.swing.JLabel();
        atmbg = new javax.swing.JLabel();
        atm = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        renter = new javax.swing.JButton();
        mainbg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        EXIT.setForeground(new java.awt.Color(255, 255, 255));
        EXIT.setText("EXIT");
        jPanel1.add(EXIT);
        EXIT.setBounds(800, 330, 100, 40);

        EXIT_ARROW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARROW3.jpg"))); // NOI18N
        jPanel1.add(EXIT_ARROW);
        EXIT_ARROW.setBounds(760, 330, 180, 40);

        ENTER_PIN_AGAIN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ENTER_PIN_AGAIN.setForeground(new java.awt.Color(255, 255, 255));
        ENTER_PIN_AGAIN.setText("ENTER PIN AGAIN");
        jPanel1.add(ENTER_PIN_AGAIN);
        ENTER_PIN_AGAIN.setBounds(770, 285, 150, 40);

        ARROWENTER.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ARROWENTER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ARROW3.jpg"))); // NOI18N
        jPanel1.add(ARROWENTER);
        ARROWENTER.setBounds(760, 285, 200, 40);

        OPTION.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        OPTION.setText("SELECT AN OPTION");
        jPanel1.add(OPTION);
        OPTION.setBounds(630, 230, 170, 17);

        wrongpin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        wrongpin.setText("WRONG PIN ENTERED");
        jPanel1.add(wrongpin);
        wrongpin.setBounds(570, 190, 330, 40);

        atmbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmbg2.jpg"))); // NOI18N
        atmbg.setText("jLabel1");
        jPanel1.add(atmbg);
        atmbg.setBounds(540, 185, 380, 240);

        atm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/atmgif0.jpg"))); // NOI18N
        atm.setText("jLabel2");
        jPanel1.add(atm);
        atm.setBounds(370, 0, 720, 780);

        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(940, 335, 80, 30);

        renter.setText("renter");
        renter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renterActionPerformed(evt);
            }
        });
        jPanel1.add(renter);
        renter.setBounds(940, 300, 70, 30);

        mainbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/w1.jpg"))); // NOI18N
        jPanel1.add(mainbg);
        mainbg.setBounds(0, 0, 1370, 780);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
          try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        trans_cancelled t1=new trans_cancelled();
         t1.setVisible(true);
         dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void renterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renterActionPerformed
        // TODO add your handling code here:
          try{sound = Applet.newAudioClip(wavFile.toURL());}
    catch(Exception e){e.printStackTrace();}
     sound.play();
        tpin t1=new tpin();
        try {
            t1.get();
        } catch (SQLException ex) {
            Logger.getLogger(wrongtpin.class.getName()).log(Level.SEVERE, null, ex);
        }
         t1.setVisible(true);
         dispose();

    }//GEN-LAST:event_renterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wrongtpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wrongtpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wrongtpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wrongtpin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wrongtpin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ARROWENTER;
    private javax.swing.JLabel ENTER_PIN_AGAIN;
    private javax.swing.JLabel EXIT;
    private javax.swing.JLabel EXIT_ARROW;
    private javax.swing.JLabel OPTION;
    private javax.swing.JLabel atm;
    private javax.swing.JLabel atmbg;
    private javax.swing.JButton exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainbg;
    private javax.swing.JButton renter;
    private javax.swing.JLabel wrongpin;
    // End of variables declaration//GEN-END:variables
}
